using System.Text;
using BeatNet.CodeGen.Analysis.ResultData;
using BeatNet.CodeGen.Generator.Util;

namespace BeatNet.CodeGen.Generator;

public class PacketGenerator
{
    public readonly PacketResult Packet;
    
    public PacketGenerator(PacketResult packet)
    {
        Packet = packet;
    }

    public void Generate(GeneratorSettings gs)
    {
        if (Packet.Fields.Count == 0)
            return;
        
        var targetNamespace = $"{gs.BaseNamespace}.Packet";
        var targetDir = Path.Combine(gs.OutputPath, "Packet");
        
        if (!Directory.Exists(targetDir))
            Directory.CreateDirectory(targetDir);
        
        var targetFile = Path.Combine(targetDir, $"{Packet.PacketName}.cs");
        
        using var sw = new StreamWriter(targetFile);
        
        sw.WriteLine("// This file was generated by BeatNet.CodeGen (PacketGenerator)");
        sw.WriteLine("// Do not modify manually");
        sw.WriteLine();
        sw.WriteLine("using BeatNet.Lib.Net.Interfaces;");
        sw.WriteLine("using BeatNet.Lib.Net.IO;");
        sw.WriteLine("using BeatNet.Lib.BeatSaber.Common;");
        sw.WriteLine("using BeatNet.Lib.BeatSaber.Generated.Enum;");
        sw.WriteLine("using BeatNet.Lib.BeatSaber.Generated.NetSerializable;");
        sw.WriteLine();
        sw.WriteLine($"namespace {targetNamespace};");
        sw.WriteLine();
        sw.WriteLine($"// ReSharper disable InconsistentNaming IdentifierTypo ClassNeverInstantiated.Global MemberCanBePrivate.Global");
        sw.WriteLine($"public sealed class {Packet.PacketName} : BaseCpmPacket");
        sw.WriteLine("{");
        
        var messageTypeType = "InternalMessageType";
        var packetTypeCase = Packet.PacketName.Replace("Packet", "");
        if (weirdPacketCaseMap.TryGetValue(packetTypeCase, out var packetTypeCaseMapped))
            packetTypeCase = packetTypeCaseMapped;
        sw.WriteLine("\t" + $"public override {messageTypeType} InternalMessageType => {messageTypeType}.{packetTypeCase};");
        
        sw.WriteLine();
        sw.WriteLine(
            FieldGenerator.GenerateFields(Packet)
        );
        sw.WriteLine(
            ConstructorGenerator.GenerateConstructor(Packet)
        );
        sw.Write(
            ReadWriteMethodGenerator.GenerateMethods(Packet, overrideKeyword: true)
        );
        sw.Write("}");
        sw.Close();
    }

    private static readonly Dictionary<string, string> weirdPacketCaseMap = new()
    {
        { "PlayerAvatar", "PlayerAvatarUpdate" },
        { "PlayerState", "PlayerStateUpdate" },
        { "PlayerSortOrder", "PlayerSortOrderUpdate" }
    };
}