name: .NET Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Server publish build (win-x64)
      run: dotnet publish BeatNet.GameServer/BeatNet.GameServer.csproj -c Release -r win-x64 --self-contained false
    - name: Server artifact publish (win-x64)
      uses: actions/upload-artifact@v4
      with:
        name: BeatNet-win-x64
        path: /home/runner/work/BeatNet/BeatNet/BeatNet.GameServer/bin/Release/net8.0/win-x64/publish/

    - name: Server publish build (linux-x64)
      run: dotnet publish BeatNet.GameServer/BeatNet.GameServer.csproj -c Release -r linux-x64 --self-contained false
    - name: Server artifact publish (linux-x64)
      uses: actions/upload-artifact@v4
      with:
        name: BeatNet-linux-x64
        path: /home/runner/work/BeatNet/BeatNet/BeatNet.GameServer/bin/Release/net8.0/linux-x64/publish/
